[workflows] Fix dart format check workflow - use && instead of &

diff --git a/.github/workflows/format-check-dart.yml b/.github/workflows/format-check-dart.yml
--- a/.github/workflows/format-check-dart.yml
+++ b/.github/workflows/format-check-dart.yml
@@ -25,4 +25,4 @@ jobs:
     - name: Check for changes
       run: |
         git ls-files -m
-        if [[ `git ls-files -m` ]]; then echo "Detected Dart formatting errors!" & exit 1; fi
+        if [[ `git ls-files -m` ]]; then echo "Detected Dart formatting errors!" && exit 1; fi
